//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lombard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Deal_id { get; set; }
        public int Item_ID { get; set; }
        public int Buyer_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public double Cost { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Item Item { get; set; }
    }
}
